const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function fixture(consent=null,configOverride={}){
  const local=new Map(),session=new Map(),handlers={},scripts=[],buttons={};
  if(consent)local.set('aurea-consent-v1',JSON.stringify({state:consent,at:Date.now()}));
  const storage=map=>({getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)});
  const elem=()=>({hidden:false,listeners:{},addEventListener(e,fn){this.listeners[e]=fn;},querySelector:()=>({focus(){}}),focus(){}});
  const choices=['accepted','rejected'].map(state=>({...elem(),dataset:{consent:state}}));
  const document={referrer:'',cookie:'',title:'Prueba',head:{append:s=>scripts.push(s)},createElement:()=>({}),addEventListener:(e,fn)=>handlers[e]=fn,dispatchEvent:()=>{},getElementById:id=>buttons[id]||(buttons[id]=elem()),querySelectorAll:s=>s==='[data-consent]'?choices:[]};
  const ctx={document,console,URL,URLSearchParams,Date,Set,localStorage:storage(local),sessionStorage:storage(session),location:{origin:'https://example.test',pathname:'/solicitud.html',search:'?utm_source=instagram&utm_campaign=prueba&email=privado',hash:'',hostname:'example.test',reload(){ctx.reloaded=true;}},history:{replaceState(...args){ctx.cleaned=args[2];}},CustomEvent:function(){},crypto:{randomUUID:()=> 'test-id'},FloristCore:require('../assets/core.js'),FLORIST_CONFIG:{ga4Id:'G-TEST123',metaPixelId:'123456789',whatsapp:'525618689260',...configOverride}};
  ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../assets/analytics.js'),'utf8'),ctx);handlers.DOMContentLoaded();return {ctx,scripts,local,session,choices};
}
test('Sin consentimiento o con rechazo no carga proveedores ni registra eventos',()=>{for(const c of [null,'rejected']){const f=fixture(c);assert.equal(f.scripts.length,0);assert.equal(f.ctx.FloristAnalytics.track('generate_lead',{request_id:'TEST'},'TEST'),false);assert.equal(f.session.size,0);}});
test('Con consentimiento inicializa solo una vista por plataforma y filtra URL',()=>{const f=fixture('accepted');assert.equal(f.scripts.length,2);assert.equal(f.ctx.dataLayer.filter(args=>args[0]==='event'&&args[1]==='page_view').length,1);assert.equal(f.ctx.fbq.queue.filter(args=>args[0]==='track'&&args[1]==='PageView').length,1);assert.ok(!f.ctx.cleaned.includes('email'));assert.ok(f.ctx.cleaned.includes('utm_campaign=prueba'));});
test('Una solicitud nunca envía Purchase y no duplica leads al repetir clic',()=>{const f=fixture('accepted'),a=f.ctx.FloristAnalytics;a.track('generate_lead',{request_id:'TEST',dedication:'privado',neighborhood:'privado',email:'privado'},'TEST');a.track('generate_lead',{request_id:'TEST'},'TEST');assert.equal(f.ctx.dataLayer.filter(args=>args[0]==='event'&&args[1]==='generate_lead').length,1);assert.equal(f.ctx.fbq.queue.filter(args=>args[0]==='track'&&args[1]==='Lead').length,1);const payload=JSON.stringify([f.ctx.dataLayer,f.ctx.fbq.queue]);assert.ok(!payload.includes('privado'));assert.ok(!payload.includes('Purchase'));assert.ok(!payload.includes('purchase'));});
test('Eventos de catálogo contienen items válidos para GA4',()=>{const f=fixture('accepted');f.ctx.FloristAnalytics.track('view_item_list',{content_ids:['1','2'],item_list_name:'catalogo'},'list');const event=f.ctx.dataLayer.find(args=>args[0]==='event'&&args[1]==='view_item_list');assert.equal(event[2].items.length,2);assert.equal(event[2].items[0].item_id,'1');});
test('Revocar consentimiento bloquea nuevos eventos y limpia atribución',()=>{const f=fixture('accepted');assert.equal(f.session.size,1);f.choices.find(c=>c.dataset.consent==='rejected').listeners.click();assert.equal(f.ctx.FloristAnalytics.track('contact',{method:'whatsapp'},'later'),false);assert.equal(f.session.size,0);assert.equal(f.ctx['ga-disable-G-TEST123'],true);assert.equal(f.ctx.reloaded,true);});
test('Aceptar sin identificadores configurados no carga proveedores',()=>{const f=fixture('accepted',{ga4Id:'',metaPixelId:''});assert.equal(f.scripts.length,0);assert.equal(f.ctx.gtag,undefined);assert.equal(f.ctx.fbq,undefined);});
