const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),files=require('../deploy-manifest.json'),products=require('../data/products.json');
test('Todos los archivos de despliegue existen y no incluyen fuentes ni secretos',()=>{for(const file of files)assert.ok(fs.existsSync(path.join(root,file)),file);assert.ok(!files.some(f=>f.includes('.git')||f.includes('.env')||f==='site.config.json'||f==='data/products.json'));});
test('Las páginas tienen títulos únicos, un h1, canonical y recursos existentes',()=>{const titles=new Set();for(const f of files.filter(f=>f.endsWith('.html'))){const html=fs.readFileSync(path.join(root,f),'utf8');const title=html.match(/<title>(.*?)<\/title>/s)?.[1];assert.ok(title);assert.ok(!titles.has(title),'Título duplicado '+f);titles.add(title);assert.equal((html.match(/<h1\b/g)||[]).length,1,f);assert.match(html,/<link rel="canonical" href="https:\/\/aurealidiaflorist.com/);for(const [,url]of html.matchAll(/(?:href|src)="(\/[^"?#]*)(?:[^"#]*)?"/g)){if(url==='/')continue;assert.ok(fs.existsSync(path.join(root,decodeURIComponent(url))),f+' → '+url);}for(const [,code]of html.matchAll(/<script type="application\/ld\+json">(.*?)<\/script>/gs))assert.doesNotThrow(()=>JSON.parse(code));}});
test('Todos los JavaScript del despliegue compilan',()=>{for(const f of files.filter(f=>f.endsWith('.js')))assert.doesNotThrow(()=>new vm.Script(fs.readFileSync(path.join(root,f),'utf8'),{filename:f}));});
test('El sitemap contiene fichas publicadas y excluye el flujo de solicitud',()=>{const xml=fs.readFileSync(path.join(root,'sitemap.xml'),'utf8');for(const p of products.filter(p=>p.status==='published'))assert.ok(xml.includes(p.slug+'.html'));assert.ok(!xml.includes('solicitud.html'));});
test('El precio de catálogo y detalle procede del mismo registro',()=>{const core=require('../assets/core.js');const catalog=fs.readFileSync(path.join(root,'catalogo.html'),'utf8');for(const p of products.filter(p=>p.status==='published')){assert.ok(catalog.includes(core.priceLabel(p)));assert.ok(fs.readFileSync(path.join(root,'arreglos/'+p.slug+'.html'),'utf8').includes(core.priceLabel(p)));}});
test('No hay pagos, disponibilidad ficticia ni contenido de confianza no validado',()=>{const html=files.filter(f=>f.endsWith('.html')).map(f=>fs.readFileSync(path.join(root,f),'utf8')).join(' ');assert.ok(!html.includes('Entrega mismo día'));assert.ok(!html.includes('5,000+'));assert.ok(!html.includes('Carlos Mendoza'));assert.ok(!html.includes('InStock'));assert.ok(!html.includes('525512345678'));});
test('Todas las imágenes tienen alt, dimensiones y srcset sin anchos duplicados',()=>{for(const f of files.filter(f=>f.endsWith('.html'))){const html=fs.readFileSync(path.join(root,f),'utf8');for(const [tag]of html.matchAll(/<img\b[^>]*>/g)){assert.match(tag,/alt="/);if(tag.includes('reference-preview'))continue;assert.match(tag,/width="\d+"/);assert.match(tag,/height="\d+"/);const set=tag.match(/srcset="([^"]*)"/)?.[1];if(set){const widths=set.split(', ').map(s=>s.split(' ').at(-1));assert.equal(new Set(widths).size,widths.length,f);}}}});
